# MASTER PRE-REQS
# Install docker, docker-compose
version: "3"
services:
  jenkins-master:
    container_name: jenkins-master
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    volumes:
    - ~/infra/jenkins_master:/var/jenkins_home
