apiVersion: v1
kind: Service
metadata:
  name: apm-server
  labels:
    app: apm-server
spec:
  selector:
    app: apm-server
  type: NodePort
  ports:
    - port: 8200
      targetPort: 8200
      name: http
