kind: ConfigMap
metadata:
  name: apm-server-config
  labels:
    k8s-app: apm-server
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"
    output.elasticsearch:
      hosts: ["0.0.0.0:9200"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apm-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
        image: docker.elastic.co/apm/apm-server:7.7.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8200
          name: apm-port
        resources: {}
        volumeMounts:
          - mountPath: /usr/share/apm-server/apm-server.yml
          name: apmserver-config
          readOnly: true
          subPath: apm-server.yml
      volumes:
        - name: apm-server-config
          configMap:
            name: apm-server-config
