apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kubernetes
      color: blue
  template:
    metadata:
      labels:
        app: hello-kubernetes
        color: blue
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080