apiVersion: batch/v1
kind: Job
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: centos:7
          command: ['/bin/bash']
          args:
            - "-c"
            - |
              echo [`date`] ping!
              sleep 5
              echo [`date`] pong!
      restartPolicy: Never
